# Generated by Django 5.2.7 on 2025-12-04 00:50

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import magazin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branduri/')),
                ('data_fond', models.DateField(blank=True, null=True, verbose_name='Data fondării')),
                ('descriere', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Branduri',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=100, unique=True)),
                ('descriere', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text='Clasa FontAwesome', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorii',
            },
        ),
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_companie', models.CharField(max_length=200, unique=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('parteneri_din', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Furnizori',
            },
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=255)),
                ('oras', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=100)),
                ('cod_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon')),
                ('adresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresa (Strada, Nr)')),
                ('judet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Județ')),
                ('localitate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localitate')),
                ('cod_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cod Poștal')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensiune', models.CharField(choices=[('Mic', 'Mic'), ('Mediu', 'Mediu'), ('Mare', 'Mare'), ('N/A', 'Nu se aplică')], default='N/A', max_length=50)),
                ('specie', models.CharField(max_length=100)),
                ('rasa', models.CharField(max_length=100)),
                ('greutate', models.DecimalField(blank=True, decimal_places=2, help_text='Greutatea medie în KG (optional)', max_digits=5, null=True)),
                ('descriere', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Animale',
                'unique_together': {('specie', 'rasa', 'dimensiune')},
            },
        ),
        migrations.CreateModel(
            name='Pret_Serviciu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret', models.DecimalField(decimal_places=2, max_digits=7)),
                ('durata', models.IntegerField(help_text='Durata estimata in minute')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.animal')),
            ],
            options={
                'verbose_name_plural': 'Prețuri Servicii',
            },
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('descriere', models.TextField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stoc', models.IntegerField(default=0)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='produse/')),
                ('data_adaugarii', models.DateTimeField(auto_now_add=True)),
                ('greutate', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazin.brand')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazin.categorie')),
                ('furnizori', models.ManyToManyField(blank=True, to='magazin.furnizor')),
            ],
            options={
                'verbose_name_plural': 'Produse',
            },
        ),
        migrations.CreateModel(
            name='Serviciu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('descriere', models.TextField()),
                ('animale', models.ManyToManyField(related_name='serviciu', through='magazin.Pret_Serviciu', to='magazin.animal')),
            ],
            options={
                'verbose_name_plural': 'Servicii',
            },
        ),
        migrations.AddField(
            model_name='pret_serviciu',
            name='serviciu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.serviciu'),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('data_inceput', models.DateField(default=datetime.date.today)),
                ('data_sfarsit', models.DateField(default=magazin.models.data_sf_default)),
                ('reducere', models.DecimalField(decimal_places=2, help_text='Procentaj, ex: 15.00 pentru 15%', max_digits=5)),
                ('categorii', models.ManyToManyField(blank=True, to='magazin.categorie')),
                ('servicii', models.ManyToManyField(blank=True, to='magazin.serviciu')),
            ],
            options={
                'verbose_name_plural': 'Oferte',
            },
        ),
        migrations.AlterUniqueTogether(
            name='pret_serviciu',
            unique_together={('serviciu', 'animal')},
        ),
    ]
