# Generated by Django 5.2.7 on 2025-10-30 07:02

import datetime
import django.db.models.deletion
import magazin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branduri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branduri/')),
                ('data_fond', models.DateField(blank=True, null=True, verbose_name='Data fondării')),
            ],
            options={
                'verbose_name_plural': 'Branduri',
            },
        ),
        migrations.CreateModel(
            name='Categorii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=100, unique=True)),
                ('descriere', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorii',
            },
        ),
        migrations.CreateModel(
            name='Furnizori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_companie', models.CharField(max_length=200, unique=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('parteneri_din', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Furnizori',
            },
        ),
        migrations.CreateModel(
            name='Animale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensiune', models.CharField(choices=[('Mic', 'Mic'), ('Mediu', 'Mediu'), ('Mare', 'Mare'), ('N/A', 'Nu se aplică')], default='N/A', max_length=50)),
                ('specie', models.CharField(max_length=100)),
                ('rasa', models.CharField(max_length=100)),
                ('greutate', models.DecimalField(blank=True, decimal_places=2, help_text='Greutatea medie în KG (optional)', max_digits=5, null=True)),
                ('descriere', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Animale',
                'unique_together': {('specie', 'rasa', 'dimensiune')},
            },
        ),
        migrations.CreateModel(
            name='Preturi_Servicii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret', models.DecimalField(decimal_places=2, max_digits=7)),
                ('durata', models.IntegerField(help_text='Durata estimata in minute')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.animale')),
            ],
            options={
                'verbose_name_plural': 'Prețuri Servicii',
            },
        ),
        migrations.CreateModel(
            name='Produse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('descriere', models.TextField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stoc', models.IntegerField(default=0)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='produse/')),
                ('data_adaugarii', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazin.branduri')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazin.categorii')),
                ('furnizori', models.ManyToManyField(blank=True, to='magazin.furnizori')),
            ],
            options={
                'verbose_name_plural': 'Produse',
            },
        ),
        migrations.CreateModel(
            name='Servicii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('descriere', models.TextField()),
                ('animale', models.ManyToManyField(related_name='servicii', through='magazin.Preturi_Servicii', to='magazin.animale')),
            ],
            options={
                'verbose_name_plural': 'Servicii',
            },
        ),
        migrations.AddField(
            model_name='preturi_servicii',
            name='serviciu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.servicii'),
        ),
        migrations.CreateModel(
            name='Oferte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('data_inceput', models.DateField(default=datetime.date.today)),
                ('data_sfarsit', models.DateField(default=magazin.models.data_sf_default)),
                ('reducere', models.DecimalField(decimal_places=2, help_text='Procentaj, ex: 15.00 pentru 15%', max_digits=5)),
                ('categorii', models.ManyToManyField(blank=True, to='magazin.categorii')),
                ('servicii', models.ManyToManyField(blank=True, to='magazin.servicii')),
            ],
            options={
                'verbose_name_plural': 'Oferte',
            },
        ),
        migrations.AlterUniqueTogether(
            name='preturi_servicii',
            unique_together={('serviciu', 'animal')},
        ),
    ]
