# Generated by Django 5.2.7 on 2025-10-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_branduri_categorii_furnizori_animale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branduri',
            name='descriere',
            field=models.TextField(blank=True, null=True),
        ),
    ]
