# Generated by Django 5.2.7 on 2025-10-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_branduri_descriere'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnizori',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
