# Generated by Django 5.2.7 on 2025-11-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0004_furnizori_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='produse',
            name='greutate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
