# Generated by Django 5.2.7 on 2025-11-04 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0005_produse_greutate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animale',
            new_name='Animal',
        ),
        migrations.RenameModel(
            old_name='Branduri',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Categorii',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Furnizori',
            new_name='Furnizor',
        ),
        migrations.RenameModel(
            old_name='Oferte',
            new_name='Oferta',
        ),
        migrations.RenameModel(
            old_name='Produse',
            new_name='Produs',
        ),
    ]
