# Generated by Django 5.2.7 on 2025-11-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0006_rename_animale_animal_rename_branduri_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preturi_Servicii',
            new_name='Pret_Serviciu',
        ),
    ]
