# Generated by Django 5.2.7 on 2025-11-04 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0007_rename_preturi_servicii_pret_serviciu'),
    ]

    operations = [
        # 1. Renumim modelul fără a-l șterge
        migrations.RenameModel(
            old_name='Servicii',
            new_name='Serviciu',
        ),
        
        # 2. Actualizăm câmpul din Oferta să arate spre noul nume
        migrations.AlterField(
            model_name='oferta',
            name='servicii',
            field=models.ManyToManyField(blank=True, to='magazin.serviciu'),
        ),
        
        # 3. Actualizăm câmpul din Pret_Serviciu să arate spre noul nume
        migrations.AlterField(
            model_name='pret_serviciu',
            name='serviciu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.serviciu'),
        ),
    ]
