# Generated by Django 5.2.7 on 2025-11-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0008_serviciu_alter_oferta_servicii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviciu',
            name='animale',
            field=models.ManyToManyField(related_name='serviciu', through='magazin.Pret_Serviciu', to='magazin.animal'),
        ),
    ]
