# Generated by Django 5.2.7 on 2025-11-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0009_categorie_slug_alter_serviciu_animale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
