# Generated by Django 5.2.7 on 2025-11-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0010_alter_categorie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Clasa FontAwesome', max_length=100, null=True),
        ),
    ]
